BookMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ecomapp.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from ecomapp.views import (
	base_view,
	category_view,
	product_view,
	cart_view,
	add_to_cart_view,
	remove_from_cart_view,
	change_item_qty,
	checkout_view,
	order_create_view,
	make_order_view,
	account_view,
	registration_view,
	login_view,
	search_view,

	)

urlpatterns = [
    url(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
    url(r'^add_to_cart/$', add_to_cart_view, name='add_to_cart'),
    url(r'^remove_from_cart/$', remove_from_cart_view, name='remove_from_cart'),
    url(r'^change_item_qty/$', change_item_qty, name='change_item_qty'),
    url(r'^cart/$', cart_view, name='cart'),
    url(r'^checkout/$', checkout_view, name='checkout'),
    url(r'^order/$', order_create_view, name='create_order'),
    url(r'^make_order/$', make_order_view, name='make_order'),
	url(r'^thank_you/$', TemplateView.as_view(template_name='thank_you.html'), name='thank_you'),
	url(r'^account/$', account_view, name='account'),
	url(r'^registration/$', registration_view, name='registration'),
	url(r'^login/$', login_view, name='login'),
	url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('base')), name='logout'),
	url(r'search/$', search_view.as_view(), name='search_views'),
    #url(r'/page/$', base_view, name='search_views'),
	url(r'^$', base_view, name='base'),
]

ecomapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from transliterate import translit
from notifications.signals import notify
from django.contrib.auth.models import User
from PIL import Image
import os
import glob
# Create your models here.


class Category(models.Model):

	name = models.CharField(verbose_name='Имя', max_length=100)
	slug = models.SlugField(blank=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('category_detail', kwargs={'category_slug': self.slug})
#автозаполнение поля слаг
def pre_save_category_slug(sender, instance, *args, **kwargs):
	if not instance.slug:
		slug = slugify(translit(str(instance.name), reversed=True))
		instance.slug = slug

pre_save.connect(pre_save_category_slug, sender=Category)

class Author(models.Model):

    name = models.CharField(verbose_name='ФИО', max_length=100)

    def __str__(self):
    	return self.name


def image_folder(instance, filename):
	filename = instance.slug + '.' + filename.split('.')[1]
	return "{0}/{1}".format(instance.slug, filename)


class Book(models.Model):

	category = models.ForeignKey(Category, verbose_name='Категория')
	author = models.ForeignKey(Author, verbose_name='Автор')
	title = models.CharField(verbose_name='Название книги', max_length=120)
	slug = models.SlugField(verbose_name='Слег')
	description = models.TextField(verbose_name='Описание')
	image = models.ImageField(verbose_name='Картинка', upload_to=image_folder)
	price = models.DecimalField(verbose_name='Цена', max_digits=9, decimal_places=2)
	available = models.BooleanField(default=True, verbose_name="Доступен")

	class Meta:
		verbose_name = "Book"
		verbose_name_plural = "Books"
		ordering = ["title", "price", "-price"]


	def __str__(self):
		return self.title


	def get_absolute_url(self):
		return reverse('product_detail', kwargs={'product_slug': self.slug})






def product_available_notification(sender, instance, *args, **kwargs):
	if instance.available:
		await_for_notify = [notification for notification in MiddlwareNotification.objects.filter(
			product=instance)]
		for notification in await_for_notify:
			notify.send(
				instance,
				recipient=[notification.user_name],
				verb='Уважаемый {0}! {1}, который Вы ждете, поступил'.format(
					notification.user_name.username,
					instance.title),
				description=instance.slug
				)
			notification.delete()


post_save.connect(product_available_notification, sender=Book)



class CartItem(models.Model):

	product = models.ForeignKey(Book, verbose_name='Книга')
	qty = models.PositiveIntegerField(verbose_name='Количество', default=1)
	item_total = models.DecimalField(verbose_name='Изменить цену', max_digits=9, decimal_places=2, default=0.00)

	def __str__(self):
		return "В корзине находится книга: {0}".format(self.product.title)


class Cart(models.Model):

	items = models.ManyToManyField(CartItem, blank=True)
	cart_total = models.DecimalField(verbose_name='Итоговая сумма', max_digits=9, decimal_places=2, default=0.00)

	def __str__(self):
		return str(self.id)



	def add_to_cart(self, product_slug):
		cart = self
		product = Book.objects.get(slug=product_slug)
		new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
		cart_items = [item.product for item in cart.items.all()]
		if new_item.product not in cart_items:
			cart.items.add(new_item)
			cart.save()


	def remove_from_cart(self, product_slug):
		cart = self
		product = Book.objects.get(slug=product_slug)
		for cart_item in cart.items.all():
			if cart_item.product == product:
				cart.items.remove(cart_item)
				cart.save()


	def change_qty(self, qty, item_id):
		cart = self
		cart_item = CartItem.objects.get(id=int(item_id))
		cart_item.qty = int(qty)
		cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
		cart_item.save()
		new_cart_total = 0.00
		for item in cart.items.all():
			new_cart_total += float(item.item_total)
		cart.cart_total = new_cart_total
		cart.save()


ORDER_STATUS_CHOICES = (
	('Принят в обработку', 'Принят в обработку'),
	('Выполняется', 'Выполняется'),
	('Оплачен', 'Оплачен')
)

class Order(models.Model):

	user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Заказчик')
	items = models.ForeignKey(Cart, verbose_name='Товары')
	total = models.DecimalField(verbose_name='Общая сумма', max_digits=9, decimal_places=2, default=0.00)
	first_name = models.CharField(verbose_name='Имя', max_length=200)
	last_name = models.CharField(verbose_name='Фамилия', max_length=200)
	phone = models.CharField(verbose_name='Номер телефона', max_length=20)
	address = models.CharField(verbose_name='Адрес', max_length=255)
	buying_type = models.CharField(verbose_name='Тип заказа', max_length=40,  choices=(('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')), default='Самовывоз')
	date = models.DateTimeField(verbose_name='Дата', auto_now_add=True)
	comments = models.TextField(verbose_name='Комментарии')
	status = models.CharField(verbose_name='Статус', max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])


	def __str__(self):
		return "Заказ №{0}".format(str(self.id))

class MiddlwareNotification(models.Model):

	user_name = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')
	product = models.ForeignKey(Book, verbose_name='Книга')
	is_notified = models.BooleanField(default=False)

	def __str__(self):
		return "Нотификация для пользователя {0} о поступлении товара {1}".format(
	   	self.user_name.username,
	   	self.product.title
	   	)

ecomapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from decimal import Decimal
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import login, authenticate
from ecomapp.forms import OrderForm, RegistrationForm, LoginForm, BookFilterForm
from ecomapp.models import Category, Book, CartItem, Cart, Order
from django.views.generic import View
from django.contrib.auth.models import User


# Create your views here.
def base_view(request):
	products = Book.objects.all()
	categories = Category.objects.all()
	product = BookFilterForm(request.GET)
	if product.is_valid():
		if product.cleaned_data["min_price"]:
			products = products.filter(price__gte=product.cleaned_data["min_price"])
		if product.cleaned_data["max_price"]:
			products = products.filter(price__lte=product.cleaned_data["max_price"])

		if product.cleaned_data["ordering"]:
			products = products.order_by(product.cleaned_data["ordering"])

	page = request.GET.get('page', 1)
	paginator = Paginator(products, 12)
	try:

		products = paginator.page(page)
	except PageNotAnInteger:
		products = paginator.page(1)
	except EmptyPage:
		products = paginator.page(paginator.num_pages)
	context = {
		'categories': categories,
		'products': products,
		'product': product,
	}
	return render(request, 'base.html', context)



#def base_view(request):
# 	try:
# 		cart_id = request.session['cart_id']
# 		cart = Cart.objects.get(id=cart_id)
# 		request.session['total'] = cart.items.count()
# 	except:
# 		cart = Cart()
# 		cart.save()
# 		cart_id = cart.id
# 		request.session['cart_id'] = cart_id
# 		cart = Cart.objects.get(id=cart_id)
# 	categories = Category.objects.all()
# 	products = Book.objects.all()
# 	context = {
# 	    'categories': categories,
# 	    'products': products,
# 	    'cart': cart
# 	}
# 	return render(request, 'base.html', context)




def product_view(request, product_slug):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)
	product = Book.objects.get(slug=product_slug)
	categories = Category.objects.all()
	context = {
	   'product': product,
	   'categories': categories,
	   'cart': cart
	}
	return render(request, 'product.html', context)


def category_view(request, category_slug):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)
	category = Category.objects.get(slug=category_slug)
	price_filter_type = request.GET.get('price_filter_type')
	print(price_filter_type)
	products_of_category = Book.objects.filter(category=category)
	categories = Category.objects.all()
	context = {
	    'category': category,
	    'products_of_category': products_of_category,
		'cart': cart,
		'categories': categories
	}
	return render(request, 'category.html', context)

def	cart_view(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)
	categories = Category.objects.all()
	context = {
	    'cart': cart,
	    'categories': categories
	}
	return render(request, 'cart.html', context)



def add_to_cart_view(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)
	product_slug = request.GET.get('product_slug')
	product = Book.objects.get(slug=product_slug)
	cart.add_to_cart(product.slug)
	new_cart_total = 0.00
	for item in cart.items.all():
		new_cart_total += float(item.item_total)
	cart.cart_total = new_cart_total
	cart.save()
	return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})


def remove_from_cart_view(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)
	product_slug = request.GET.get('product_slug')
	product = Book.objects.get(slug=product_slug)
	cart.remove_from_cart(product.slug)
	new_cart_total = 0.00
	for item in cart.items.all():
		new_cart_total += float(item.item_total)
	cart.cart_total = new_cart_total
	cart.save()
	return JsonResponse(
		{'cart_total': cart.items.count(),
		'cart_total_price': cart.cart_total})


def change_item_qty(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)
	qty = request.GET.get('qty')
	item_id = request.GET.get('item_id')
	cart.change_qty(qty, item_id)
	cart_item = CartItem.objects.get(id=int(item_id))
	return JsonResponse(
		{'cart_total': cart.items.count(),
		'item_total': cart_item.item_total,
		'cart_total_price': cart.cart_total})



def checkout_view(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)
	categories = Category.objects.all()
	context = {
        'cart': cart,
        'categories': categories
	}
	return render(request, 'checkout.html', context)


def order_create_view(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)
	form = OrderForm(request.POST or None)
	categories = Category.objects.all()
	context = {
	   'form': form,
	   'cart': cart,
	   'categories': categories
	}
	return render(request, 'order.html', context)



def make_order_view(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)
	form = OrderForm(request.POST or None)
	categories = Category.objects.all()
	if form.is_valid():
		name = form.cleaned_data['name']
		last_name = form.cleaned_data['last_name']
		phone = form.cleaned_data['phone']
		buying_type = form.cleaned_data['buying_type']
		address = form.cleaned_data['address']
		comments = form.cleaned_data['comments']
		new_order = Order.objects.create(
			user=request.user,
			items=cart,
			total=cart.cart_total,
			first_name=name,
			last_name=last_name,
			phone=phone,
			address=address,
			buying_type=buying_type,
			comments=comments
			)
		del request.session['cart_id']
		del request.session['total']
		return HttpResponseRedirect(reverse('thank_you'))
	return render(request, 'order.html', {'categories': categories})



def account_view(request):
	order = Order.objects.filter(user=request.user).order_by('-id')
	categories = Category.objects.all()
	for item in order:
		for new_item in item.items.items.all():
			print(new_item.item_total)
	context = {
		'order': order,
		'categories': categories
	}
	return render(request, 'account.html', context)

def registration_view(request):
	form = RegistrationForm(request.POST or None)
	categories = Category.objects.all()
	if form.is_valid():
		new_user = form.save(commit=False)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		email = form.cleaned_data['email']
		first_name = form.cleaned_data['first_name']
		last_name = form.cleaned_data['last_name']
		new_user.username = username
		new_user.set_password(password)
		new_user.first_name = first_name
		new_user.last_name = last_name
		new_user.email = email
		new_user.save()
		login_user = authenticate(username=username, password=password)
		if login_user:
			login(request, login_user)
			return HttpResponseRedirect(reverse('base'))
	context = {
		'form': form,
		'categories': categories
	}
	return render(request, 'registration.html', context)


def login_view(request):
	form = LoginForm(request.POST or None)
	categories = Category.objects.all()
	if form.is_valid():
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		login_user = authenticate(username=username, password=password)
		if login_user:
			login(request, login_user)
			return HttpResponseRedirect(reverse('base'))
	context = {
		'form': form,
		'categories': categories
	}
	return render(request, 'login.html', context)


class search_view(View):

	template_name = 'search.html'
	def get(self, request, *args, **kwargs):
		query = self.request.GET.get('q')
		categories = Category.objects.all()
		founded_articles = Book.objects.filter(
			Q(title__icontains=query)|
			Q(description__icontains=query))
		context = {
			'founded_articles': founded_articles,
			'categories': categories
		}
		return render(self.request, self.template_name, context)

ecomapp/templates/account.html
{% extends 'base.html' %}


{% block content %}

<h3 class="text-center">Личный кабинет пользователя {{ request.user }}</h3>
<hr>
<h4 class='text-center'>Ваши заказы</h4>
<table class='table'>
<tr style='background:lightgreen;'>
	<td class='text-center'>Номер заказа</td>
	<td class='text-center'>Дата заказа</td>
	<td class='text-center'>Статус заказа</td>
	<td class='text-center'>Стоимость заказа</td>
	<td class='text-center'>Детали заказа</td>
	<td></td>
</tr>
{% for item in order %}
<tr>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.id }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.date }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.status }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.total }} руб.</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'><button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal-{{ item.id }}">
  Детали заказа
</button></td>
</tr>
{% endfor %}
</table>
<!-- Button trigger modal -->

<!-- Modal -->
{% for item in order %}
<div class="modal fade" id="myModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Заказ № {{ item.id }}</h4>
      </div>
      <div class="modal-body">
      <h3>Товар</h3>
        <table class='table'>
        	{% for order_item in item.items.items.all %}
	        	<tr>
	       			<td>{{ order_item.product.title }}</td>
	       			<td>{{ order_item.qty }} шт.</td>
	       			<td>{{ order_item.item_total }} руб.</td>
	        	</tr>
        	{% endfor %}
        		 <tr>
	        		<td></td>
	        		<td>Итого</td>
	        		<td><strong>{{ item.items.cart_total }} руб.</strong></td>
	        	</tr>
        </table>
   		<h3>Заказчик</h3>
   		 <p>Имя: {{ item.first_name }}</p>
   		 <p>Фамилия: {{ item.last_name }}</p>
   		 <p>Телефон: {{ item.phone }}</p>
   		 <h3>Тип доставки</h3>
   		 <p>{% if item.buying_type == 'self' %} Самовывоз {% else %}Доставка{% endif %}</p>
   		 <p>{% if item.buying_type == 'delivery' %} {{ item.address }}{% endif %}</p>
   		 <h3>Комментарии к заказу</h3>
   		 <p>{{ item.comments }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

ecomapp/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h3 class="text-center"><strong>Ваша корзина</strong></h3>
<br>
{% if cart.items.count > 0 %}
<div class='my-cart'>
<table class="table">
	<tr>
		<td class="text-center"><strong>Товар</strong></td>
		<td class="text-center"><strong>Количество</strong></td>
		<td class="text-center"><strong>Цена</strong></td>
		<td class="text-center"></td>
	</tr>
{% for item in cart.items.all %}
	<tr class='cart-item-{{ item.product.id }}'>
		<td class="text-center">{{ item.product.title }}</td>
		<td class="text-center">
			<form action='' method="GET">
				<input type="number" name="qty" class="cart-item-qty" data-id='{{ item.id }}' value='{{ item.qty }}' min='1' style="width: 50px;">
		</form>		
		</td>
		<td class="text-center" id='cart-item-total-{{ item.id }}'>{{ item.item_total }} руб.</td>
		<td class="text-center"><a href='#' class='remove_from_cart' data-slug='{{ item.product.slug }}' data-id='{{ item.product.id }}'><button class="btn btn-default">Удалить из корзины</button></a></td>
</tr>
{% endfor %}
<tr>
	<td></td>
	<td class="text-center"><strong> Итого:</strong> </td>
	<td class="text-center" id="cart-total-price"><strong>{{ cart.cart_total }} руб.</strong></td>
	<td></td>
</tr>		
</table>
<br>
<a href='{% url "checkout" %}' class="pull-right"><button class="btn btn-info">Предварительный заказ</button></a>
</div>
<h3 class="cart-empty"></h3>
{% else %}
<h3 class="text-center">Ваша корзина пуста</h3>
{% endif %}
<script src='{% static "js/jquery.js" %}'></script>
<script>
	$(document).ready(function(){
		$('.cart-empty').css('display', 'none')
		$('.remove_from_cart').on('click', function(e){
			e.preventDefault()
			product_slug = $(this).attr('data-slug')
			item_product_id = $(this).attr('data-id')
			data = {
				product_slug: product_slug
			}

			$.ajax({
				type: "GET",
				url: '{% url "remove_from_cart" %}',
				data: data,
				success: function(data){
					$("#cart_count").html(data.cart_total)
					$('.cart-item-'+item_product_id).css('display', 'none')
					$('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' руб.</strong>')
					if(parseInt(data.cart_total) == 0){
						$('.my-cart').css('display', 'none')
						$('.cart-empty').css('display', 'block')
						$('.cart-empty').html('<h3 class="text-center">Ваша корзина пуста</h3>')
					}
				}
			})
		})
	})
		$(document).ready(function() {
		$('.cart-item-qty').on('click', function(){
			qty = $(this).val()
			item_id = $(this).attr('data-id')
			data = {
				qty: qty,
				item_id: item_id
			}
			$.ajax({
				type: "GET",
				url: '{% url "change_item_qty" %}',
				data: data,
				success: function(data){
					$('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(2) + 'руб.')
					$('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' руб.</strong>')
		}
	})
		})	
	})
</script>
{% endblock content %}

ecomapp/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
<h2>{{ category.name }}</h2>
<hr>
{% for product in products_of_category %}
<div class="col-sm-4">
    <div class="thumbnail" style="height: 490px; position: relative;">
<a href='{{ product.get_absolute_url }}'> <img src='{{ product.image.url }}' style="width: 233px; height: 323px"></a>
<h5 class="text-center"><strong><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></strong></h5>
<p class="text-center" style="font-size: 20px"><strong> Цена: {{ product.price }}руб.</strong></p>
{% if request.user.is_authenticated %}
    <p class="text-center"><a href='#' class='add_to_cart' data-slug='{{ product.slug }}'>
        <button class='btn btn-danger'>Добавить в корзину</button></a></p>
    {% else %}
<p class='text-center'>Заказывать товар могут только авторизированные пользователи. Пожалуйста, <a href='#'>войдите</a> или <a href='#'>зарегистрируйтесь</a></p>{% endif %}
</div>
    </div>
{% endfor %}
</div>
<script src='{% static "js/jquery.js" %}'></script>
<script>
$(document).ready(function(){
	$('.add_to_cart').on('click', function(e){
		e.preventDefault()
		product_slug = $(this).attr('data-slug')
		data = {
			product_slug: product_slug
		}
		$.ajax({
			type: "GET",
			url: '{% url "add_to_cart" %}',
			data: data,
			success: function(data){
				$("#cart_count").html(data.cart_total)
			}
		})
	})
})
</script>
{% endblock content %}

ecomapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class='text-center'>Авторизация</h3>
<hr>
<div class='col-sm-8 col-sm-offset-2'>
<form action='' method='POST'>
	{% csrf_token %}
	{{ form|crispy }}
	<input type='submit' class='btn btn-success btn-block' value="Войти в систему">
</form>
</div>
{% endblock content %}

ecomapp/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class='text-center'>Оформление заказа</h3>
<hr>
<form action='{% url "make_order" %}' method="POST">
{% csrf_token %}
<div class='col-sm-4'>
	{{ form.name|as_crispy_field }}
</div>
<div class='col-sm-4'>
	{{ form.last_name|as_crispy_field }}
</div>
<div class='col-sm-4'>
	{{ form.phone|as_crispy_field }}
</div>
{{ form.buying_type|as_crispy_field }}
{{ form.address|as_crispy_field }}
{{ form.date|as_crispy_field }}
{{ form.comments|as_crispy_field }}
<input type='submit' class='btn btn-success' value='Оформить заказ'>
</form>
<script src="{% static 'js/jquery.js' %}"></script>
<script>
	$(document).ready(function(){
		$('#div_id_address').css('display', 'none')
		$('#id_buying_type').on('click', function(){
			buying_type = $(this).val()
			if(buying_type == 'delivery'){
				$('#div_id_address').css('display', 'block')
			}else{
				$('#div_id_address').css('display', 'none')
			}
		})
		$('#id_date_month').css('width', '120px')
		$('#id_date_month').css('display', 'inline')
		$('#id_date_year').css('width', '120px')
		$('#id_date_year').css('display', 'inline')
		$('#id_date_day').css('width', '120px')
		$('#id_date_day').css('display', 'inline')
	})

</script>
{% endblock content %}